In [2]:
pip install pandas pyreadstat numpy matplotlib

Requirement already satisfied: pandas in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.2)
Requirement already satisfied: pyreadstat in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.3.4)
Requirement already satisfied: numpy in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (2.4.4)
Requirement already satisfied: matplotlib in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.10.9)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dharm\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: narwhals>=2.10.1 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pyreadstat) (2.21.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\dharm\appdata\roaming\python\python314\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\dharm\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
pip install seaborn plotly

Requirement already satisfied: seaborn in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (0.13.2)
Requirement already satisfied: plotly in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (6.7.0)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from seaborn) (3.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from plotly) (2.21.0)
Requirement already satisfied: packaging in c:\users\dharm\appdata\roaming\python\python314\site-packages (from plotly) (26.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dharm\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dharm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\dharm\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import pyreadstat

ae, meta = pyreadstat.read_sas7bdat("C:/Users/dharm/Clinical_Trial_SDTM_Project/raw_data/ae.sas7bdat")

print(ae.head())

                       PROJ_ID SITE_ID     SUBID  STATE  EVENT_NO  \
0  DN-101 Protocol No. 011-007     001  001-0003    5.0       9.0
1  DN-101 Protocol No. 011-007     001  001-0003    5.0       9.0
2  DN-101 Protocol No. 011-007     001  001-0003    5.0       9.0
3  DN-101 Protocol No. 011-007     001  001-0003    5.0       9.0
4  DN-101 Protocol No. 011-007     001  001-0003    5.0       9.0

                              EVENT_ID            ID  \
0  Adverse Event/Serious Adverse Event  2.603014e+09
1  Adverse Event/Serious Adverse Event  2.645893e+09
2  Adverse Event/Serious Adverse Event  2.680725e+09
3  Adverse Event/Serious Adverse Event  2.680743e+09
4  Adverse Event/Serious Adverse Event  2.682100e+09

                         AETERM  AESTDT_  AEENDT_  ...  M_PT  M_SOURCE  \
0                       fatigue     15.0    248.0  ...
1                        anemia     35.0      NaN  ...
2              arthralgia knees     37.0    187.0  ...
3  numbness tingling fingertips     51.0    162.0  ...
4                   hot flashes     14.0      NaN  ...

   M_SCORE  M_MTIME  M_SOC        M_TIME  M_DICT  M_HLT  M_PROD  M_IS_P
0      NaN      NaN         1.471792e+09                            NaN
1      NaN      NaN         1.471792e+09                            NaN
2      NaN      NaN         1.473884e+09                            NaN
3      NaN      NaN         1.473884e+09                            NaN
4      NaN      NaN         1.473962e+09                            NaN

[5 rows x 74 columns]

In [6]:
ae.shape

(5880, 74)

In [7]:
ae.columns.tolist()

['PROJ_ID',
 'SITE_ID',
 'SUBID',
 'STATE',
 'EVENT_NO',
 'EVENT_ID',
 'ID',
 'AETERM',
 'AESTDT_',
 'AEENDT_',
 'AEONGO',
 'AETOXGR',
 'AEPACN',
 'AEPACN_A',
 'AEPACN_B',
 'AEACN',
 'AEACN_A',
 'AEACN_B',
 'AEDACN',
 'AEDACN_A',
 'AEDACN_B',
 'AEACOTH',
 'AEACOTH1',
 'AEACOTH2',
 'AEACOTH3',
 'AEACO3OT',
 'AEOUT',
 'AERELP',
 'AERELA',
 'AERELD',
 'AESER',
 'AESCONG',
 'AESDISAB',
 'AESDTH',
 'AESHOSP',
 'AESLIFE',
 'AESINTER',
 'AESOTH',
 'AESOTHC',
 'SAEIRDT_',
 'SAEDDT_',
 'SAEAUTOP',
 'SAEHADT_',
 'SAEHDDT_',
 'SAECOM1',
 'SAECOM2',
 'SAECOM3',
 'SAEPRED',
 'SAEDRED',
 'SAEPST',
 'SAEST',
 'SAEDST',
 'SAEPRR',
 'SAERR',
 'SAEDRR',
 'SAEDESC1',
 'SAEDESC2',
 'SAEDESC3',
 'SAEDESC4',
 'SAEDESC5',
 'SAEDESC6',
 'M_HLGT',
 'M_LLT',
 'M_USER',
 'M_PT',
 'M_SOURCE',
 'M_SCORE',
 'M_MTIME',
 'M_SOC',
 'M_TIME',
 'M_DICT',
 'M_HLT',
 'M_PROD',
 'M_IS_P']

In [8]:
ae["SUBID"].nunique()

441

In [9]:
ae["SUBID"].duplicated().sum()

np.int64(5439)

In [10]:
# Total adverse events
len(ae)

5880

In [11]:
# Patients with at least one AE

ae["SUBID"].nunique()

441

In [12]:
# Most common adverse events

ae.columns

Index(['PROJ_ID', 'SITE_ID', 'SUBID', 'STATE', 'EVENT_NO', 'EVENT_ID', 'ID',
       'AETERM', 'AESTDT_', 'AEENDT_', 'AEONGO', 'AETOXGR', 'AEPACN',
       'AEPACN_A', 'AEPACN_B', 'AEACN', 'AEACN_A', 'AEACN_B', 'AEDACN',
       'AEDACN_A', 'AEDACN_B', 'AEACOTH', 'AEACOTH1', 'AEACOTH2', 'AEACOTH3',
       'AEACO3OT', 'AEOUT', 'AERELP', 'AERELA', 'AERELD', 'AESER', 'AESCONG',
       'AESDISAB', 'AESDTH', 'AESHOSP', 'AESLIFE', 'AESINTER', 'AESOTH',
       'AESOTHC', 'SAEIRDT_', 'SAEDDT_', 'SAEAUTOP', 'SAEHADT_', 'SAEHDDT_',
       'SAECOM1', 'SAECOM2', 'SAECOM3', 'SAEPRED', 'SAEDRED', 'SAEPST',
       'SAEST', 'SAEDST', 'SAEPRR', 'SAERR', 'SAEDRR', 'SAEDESC1', 'SAEDESC2',
       'SAEDESC3', 'SAEDESC4', 'SAEDESC5', 'SAEDESC6', 'M_HLGT', 'M_LLT',
       'M_USER', 'M_PT', 'M_SOURCE', 'M_SCORE', 'M_MTIME', 'M_SOC', 'M_TIME',
       'M_DICT', 'M_HLT', 'M_PROD', 'M_IS_P'],
      dtype='str')

In [13]:
# top adverse events

ae["AETERM"].value_counts().head(10)

AETERM
fatigue          198
Fatigue          186
neutropenia      140
anemia            88
leukopenia        83
alopecia          82
Neutropenia       82
Alopecia          79
hyperglycemia     68
Hyperglycemia     68
Name: count, dtype: int64

In [14]:
# Check severity (if exists)

ae["AETOXGR"].value_counts()

AETOXGR
1.0    3333
2.0    1642
3.0     679
4.0     204
5.0      21
Name: count, dtype: int64

In [15]:
ae["AETOXGR_LABEL"] = ae["AETOXGR"].map({
    1.0: "Mild",
    2.0: "Moderate",
    3.0: "Severe",
    4.0: "Life-threatening or disabling",
    5.0: "Death related to AE"
})

In [16]:
ae[["AETOXGR", "AETOXGR_LABEL"]].head()

   AETOXGR AETOXGR_LABEL
0      1.0          Mild
1      1.0          Mild
2      1.0          Mild
3      1.0          Mild
4      1.0          Mild

In [17]:
ae["AETOXGR_LABEL"].value_counts()

AETOXGR_LABEL
Mild                             3333
Moderate                         1642
Severe                            679
Life-threatening or disabling     204
Death related to AE                21
Name: count, dtype: int64

In [18]:
ae[ae["AETOXGR"] >= 3]

,PROJ_ID,SITE_ID,SUBID,STATE,EVENT_NO,EVENT_ID,ID,AETERM,AESTDT_,AEENDT_,...,M_SOURCE,M_SCORE,M_MTIME,M_SOC,M_TIME,M_DICT,M_HLT,M_PROD,M_IS_P,AETOXGR_LABEL
22,DN-101 Protocol No. 011-007,001,001-0005,5.0,9.0,Adverse Event/Serious Adverse Event,2.925802e+09,hemorrhage GI,153.0,167.0,...,,NaN,NaN,,1.486581e+09,,,,NaN,Death related to AE
23,DN-101 Protocol No. 011-007,001,001-0005,5.0,9.0,Adverse Event/Serious Adverse Event,4.960903e+09,sepsis,153.0,167.0,...,,NaN,NaN,,1.519661e+09,,,,NaN,Severe
24,DN-101 Protocol No. 011-007,001,001-0005,5.0,9.0,Adverse Event/Serious Adverse Event,4.961587e+09,acute renal failure,153.0,167.0,...,,NaN,NaN,,1.519662e+09,,,,NaN,Life-threatening or disabling
25,DN-101 Protocol No. 011-007,001,001-0005,5.0,9.0,Adverse Event/Serious Adverse Event,4.962110e+09,metabolic acidosis,153.0,167.0,...,,NaN,NaN,,1.519663e+09,,,,NaN,Life-threatening or disabling
26,DN-101 Protocol No. 011-007,001,001-0005,5.0,9.0,Adverse Event/Serious Adverse Event,4.962627e+09,hypotension,153.0,167.0,...,,NaN,NaN,,1.519664e+09,,,,NaN,Life-threatening or disabling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5871,DN-101 Protocol No. 011-007,619,619-0004,5.0,9.0,Adverse Event/Serious Adverse Event,3.332398e+09,Hypercalcemia,34.0,43.0,...,,NaN,NaN,,1.498597e+09,,,,NaN,Severe
5872,DN-101 Protocol No. 011-007,619,619-0004,5.0,9.0,Adverse Event/Serious Adverse Event,3.332441e+09,Hypokaliemia,34.0,43.0,...,,NaN,NaN,,1.498597e+09,,,,NaN,Severe
5873,DN-101 Protocol No. 011-007,619,619-0004,5.0,9.0,Adverse Event/Serious Adverse Event,3.414245e+09,Prostate cancer disease progression,44.0,44.0,...,,NaN,NaN,,1.499905e+09,,,,NaN,Death related to AE
5877,DN-101 Protocol No. 011-007,619,619-0007,5.0,9.0,Adverse Event/Serious Adverse Event,3.431078e+09,Anaemia,76.0,NaN,...,,NaN,NaN,,1.507407e+09,,,,NaN,Severe
5878,DN-101 Protocol No. 011-007,619,619-0007,5.0,9.0,Adverse Event/Serious Adverse Event,3.904866e+09,Anaemia,97.0,104.0,...,,NaN,NaN,,1.508422e+09,,,,NaN,Severe

In [19]:
ae.groupby("SUBID")["AETOXGR"].max().value_counts()

AETOXGR
3.0    142
2.0    135
4.0     97
1.0     46
5.0     21
Name: count, dtype: int64